### ISSUE TITLE
'-b' option does not work

### ISSUE THREAD

**Issue by j5shi** [juho-p/fatty#10]
I tried `fatty -b "bash"` in fatty and it starts bash in a new window instead of in a tab.

**Comment by juho-p** [comment]
That `-b` option is for opening new window with multiple tabs.

I guess you mean some functionality that would open a tab into existing terminal window. I've considered such functionality before and I think it's a good idea, but I won't implement it any time soon, since it would probably take quite a lot of effort to do and I don't have that much extra time to spend on this project.

**Comment by j5shi** [comment]
Ok, got it, thanks.
