### ISSUE TITLE
Add support for WSL

### ISSUE THREAD

**Issue by jchayan** [juho-p/fatty#24]
Does FaTTY supports windows subsystem for linux? If no, how hard can it be to accomplish it?

**Comment by juho-p** [comment]
Unfortunately, Fatty is really targeted for Cygwin only and there is no plans for WSL.

I guess it could be possible to implement support for WSL. Currently, there are decent amount of code that requires POSIX-API (provided by Cygwin) and that would have to be abstracted away. AFAIK, WSL support would require Fatty to be pure Windows application (otherwise it would still require Cygwin) and it would communicate with bash (or other shell) with sockets (at least that is my understanding). Maybe it's possible, but it's also a lot of work.

Sorry, too much work for me to do it in any near future (hah, like every other feature for this project). If someone gets interested enough in this and implement WSL support (unlikely), then I guess I could merge it. Or you can always for and create new different project for WSL supported fatty, I don't mind.
