### ISSUE TITLE
Can you please pass this repo to someone that has time to maintain it?

### ISSUE THREAD

**Issue by mskyaxl** [juho-p/fatty#38]
Hi,

Can you please pass this repo to @paolo-sz? It looks like he has more time to update this repo.

Thanks!

Best,
Alex

**Comment by paolo-sz** [comment]
Hi Alex,

thanks for the trust but I'm not really sure I will be the right one that could take charge of maintaining (seriously) this repo.
What I'm doing on my branch is basically keeping it aligned with old parent mintty but I did that mainly for my personal usage. This means I'm pretty sure I will have no time to follow any pull request or reported bug that may happen.
Even now there are some issues in the code (sometime it crashes unexpectedly) but they are pretty rare and I basically survive with them... which is not a good behavior for anything "official"...

BR,
Paolo.

**Comment by juho-p** [comment]
It's a decent suggestion. I'm not against it, since I haven't really maintained this in a long time. Of course that would require someone that would be active in maintaining this.

If for example Paolo changes mind and would like to maintain "official" version, I can transfer ownership (though I'd really prefer no crashing!).

I'll leave this issue open. If someone has active fork and comments here to say they'd want ownership, I can then consider it.

**Comment by juho-p** [comment]
Closing since there's not that much interest...
