### ISSUE TITLE
make: Error when running make

### ISSUE THREAD

**Issue by hue-bui** [juho-p/fatty#40]
I downloaded the latest versions of all the required packages from cygwin64 download UI, then followed the given instructions to install fatty, but I got the below errors when running **make**:

`windres --preprocessor 'gcc -E -xc -DRC_INVOKED -MMD -MT build/res.o -DTARGET=x86_64-pc-cygwin -D_GNU_SOURCE -DNDEBUG' res.rc res.o
/bin/sh: gcc -E -xc -DRC_INVOKED -MMD -MT build/res.o -DTARGET=x86_64-pc-cygwin -D_GNU_SOURCE -DNDEBUG: No such file or directory
windres: preprocessing failed.
make[1]: *** [Makefile:52: build/res.o] Error 1
make[1]: Leaving directory '/cygdrive/c/Users/bongh/fatty/src'
make: *** [Makefile:2: exe] Error 2
`

I also got a warning below, but not sure if that is a real issue:

`gcc -DTARGET=x86_64-pc-cygwin -D_GNU_SOURCE -DNDEBUG -std=gnu99 -include std.h -Wall -Wextra -Wundef -Os -c termmouse.c -o build/termmouse.o -MMD -MT build/termmouse.o
termmouse.c: In function ‘term_mouse_click’:
termmouse.c:336:23: warning: implicit conversion from ‘mouse_button’ to ‘enum <anonymous>’ [-Wenum-conversion]
  336 |     term->mouse_state = b;
      |                       ^
termmouse.c: In function ‘term_mouse_move’:
termmouse.c:515:43: warning: implicit conversion from ‘enum <anonymous>’ to ‘mouse_button’ [-Wenum-conversion]
  515 |       send_mouse_event(term, MA_MOVE, term->mouse_state, mods, bp);
      | `

Could you please help guide me how to overcome the issue? Thanks a lot!

**Comment by juho-p** [comment]
Thyanks for reporting this issue. The build is (was) indeed broken with latest cygwin due to some windres (Cygwin Windows resource compiler) changes. This should be now fixed (or rather worked around?) in 7f754703a6978ec43f6c93215d64fb889fb43996

The warning is due to improved gcc behaviour. The code is slightly wrong there, but it works so I'm too lazy to fix it.

You can try pulling latest changes and see if it works now, if you like.
